version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: lolcathost
    main: ./cmd/lolcathost
    binary: lolcathost
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.appVersion={{.Version}}

archives:
  - id: lolcathost
    format: tar.gz
    name_template: "lolcathost-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "lolcathost-{{ .Version }}-checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^Merge"
      - "^WIP"

release:
  github:
    owner: lukaszraczylo
    name: lolcathost
  name_template: "Release {{.Version}}"
  draft: false
  prerelease: auto

brews:
  - repository:
      owner: lukaszraczylo
      name: homebrew-taps
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: https://github.com/lukaszraczylo/lolcathost
    description: "Dynamic host management tool for macOS and Linux with TUI"
    license: MIT
    test: |
      system "#{bin}/lolcathost", "--version"
