version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: lolcathost
    main: ./cmd/lolcathost
    binary: lolcathost
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.appVersion={{.Version}}

archives:
  - id: lolcathost
    formats: [tar.gz]
    name_template: "lolcathost-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "lolcathost-{{ .Version }}-checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^Merge"
      - "^WIP"

release:
  github:
    owner: lukaszraczylo
    name: lolcathost
  name_template: "Release {{.Version}}"
  draft: false
  prerelease: auto

homebrew_casks:
  - repository:
      owner: lukaszraczylo
      name: homebrew-taps
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Casks
    homepage: https://github.com/lukaszraczylo/lolcathost
    description: "Dynamic host management tool with TUI"
    license: MIT
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr",
                           args: ["-dr", "com.apple.quarantine", "#{staged_path}/lolcathost"]
          end

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum
    output: true
